using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConfigureMiddlewareExample
{
	public class Startup
	{
		// This method gets called by the runtime. Use this method to add services to the container.
		// For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
		public void ConfigureServices(IServiceCollection services)
		{

		}
		public void Configure(IApplicationBuilder app)
		{
			
			app.Use(async (context, next) =>
			{
				await context.Response.WriteAsync($"This text was generated by the app.Use middleware. Request path is: {context.Request.Path.Value}");
				await next.Invoke();
			});

			app.Run(async (context) =>
			{
				await context.Response.WriteAsync("This text was generated by the app.Run middleware.");
			});
		}



		// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
		/*public void Configure(IApplicationBuilder app, IHostingEnvironment env)
		{
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}

			app.Run(async (context) =>
			{
				await context.Response.WriteAsync("Hello World!");
			});
		}*/
	}
}
